/**
 * 精灵资源配置 — 唯一事实来源
 *
 * 新增 PNG 精灵只需在这里加一行，BootScene 和 AssetGenerator 自动同步。
 */
export const PNG_SPRITE_KEYS = [
  'unit_worker',
  'unit_rifleman',
  'unit_arcane_heavy',
  'unit_battle_mage',
  'unit_magitech_mech',
  'bld_cc_empire',
  'bld_cc_federation',
  'bld_barracks',
  'bld_factory',
  'bld_refinery',
  'bld_power_plant',
  'bld_wall',
  'unit_scout_bike',
  'unit_transport',
  'unit_arcane_guard',
  'unit_hammer_squad',
  'unit_grenadier',
  'hero_isabelle',
  'hero_marcus',
  'hero_sebastian',
  'hero_eileen',
  'bld_turret',
  'bld_ancient_archive',
  'bld_assembly_workshop',
  'bld_repair_depot',
  'bld_alchemy_lab',
  'bld_void_resonator',
  'bld_teleport_gate',
  'ui_crystal',
  'proj_bullet',
  'proj_magic_bolt',
  'proj_cannon',
  'unit_void_probe',
  'unit_assault_worker',
  'neutral_crystal_wisp',
  'neutral_feral_mech',
  'neutral_mountain_beast',
  'neutral_trade_outpost',
  'neutral_ancient_shrine',
  'neutral_abandoned_mine',
  'neutral_watchtower',
  'unit_arcane_cannon',
  'unit_mobile_workshop',
  'unit_alchemy_colossus',
  'unit_unstable_crystal',
  'unit_rune_titan',
  'unit_arcane_bastion',
  'unit_corrosion_beast',
  'unit_void_walker',
  'unit_siege_engine',
  // 批2: 霜脊王国
  'unit_frost_guard',
  'unit_crystal_catapult',
  'unit_deep_destroyer',
  'bld_cc_frostridge',
  'bld_deep_mine',
  'hero_frost_a',
  'hero_frost_b',
  // 批3: 翡翠邦联
  'unit_jade_scout',
  'unit_mercenary_sword',
  'bld_cc_jade',
  'bld_trade_post',
  'hero_jade_a',
  'hero_jade_b',
  // ===== UI 皮肤 (批1: 暗紫魔导+金描边) =====
  'skin_panel_console',
  'skin_panel_top',
  'skin_btn_normal',
  'skin_btn_hover',
  'skin_btn_active',
  'skin_card',
  // UI 图标 (24x24)
  'ui_icon_crystal',
  'ui_icon_industry',
  'ui_icon_supply',
  'ui_icon_timer',
  // UI 装饰
  'ui_deco_gear',
  'ui_frame_portrait',
  'ui_minimap_frame',
  // 主菜单
  'ui_menu_bg',
  'ui_logo',
] as const;

/** UI 皮肤/图标纹理 key (需线性采样, 不受 pixelArt nearest 影响) */
export const UI_SKIN_KEYS = [
  'skin_panel_console', 'skin_panel_top', 'skin_btn_normal', 'skin_btn_hover', 'skin_btn_active', 'skin_card',
  'ui_icon_crystal', 'ui_icon_industry', 'ui_icon_supply', 'ui_icon_timer',
  'ui_deco_gear', 'ui_frame_portrait', 'ui_minimap_frame',
  'ui_menu_bg', 'ui_logo',
] as const;